SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Maintenance_Alerts;
TRUNCATE TABLE Charger_Error_Log;
TRUNCATE TABLE Billing_Records;
TRUNCATE TABLE Charging_Sessions;
TRUNCATE TABLE Reservations;
TRUNCATE TABLE Pricing_Rules;
TRUNCATE TABLE EV_Chargers;
TRUNCATE TABLE Parking_Spots;
TRUNCATE TABLE Parking_Zones;
TRUNCATE TABLE Vehicles;
TRUNCATE TABLE Wallets;
TRUNCATE TABLE Users;
SET FOREIGN_KEY_CHECKS = 1;

