DROP TABLE IF EXISTS Maintenance_Alerts;
DROP TABLE IF EXISTS Charger_Error_Log;
DROP TABLE IF EXISTS Billing_Records;
DROP TABLE IF EXISTS Charging_Sessions;
DROP TABLE IF EXISTS Reservations;
DROP TABLE IF EXISTS Pricing_Rules;
DROP TABLE IF EXISTS EV_Chargers;
DROP TABLE IF EXISTS Parking_Spots;
DROP TABLE IF EXISTS Parking_Zones;
DROP TABLE IF EXISTS Vehicles;
DROP TABLE IF EXISTS Wallets;
DROP TABLE IF EXISTS Users;

